apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eck-elasticsearch
  namespace: argocd
spec:
  destination:
    namespace: eck
    server: https://kubernetes.default.svc
  project: dev
  source:
    helm:
      valueFiles:
      - values.yaml
    path: eck-elasticsearch
    repoURL: https://github.com/92phantom/monitoring.git
    targetRevision: HEAD